---
- name: Setup K8S configuration
  ansible.builtin.copy:
    src: "{{ role_path }}/files/k8s.conf"
    dest: /etc/sysctl.d/k8s.conf
    mode: '0644'

- name: Delete default crio-o network configuration
  ansible.builtin.file:
    state: absent
    path: /etc/cni/net.d/100-crio-bridge.conf

# Get previous cni0 IP and change the range!
- name: Get actual network CIDR
  ansible.builtin.command: ip a | grep -m1 10.42. | awk '{print $2}' |sed -r 's|/32+|/24|g'
  register: actual_cidr
  changed_when: false

- name: Setup new cri-o network configuration
  ansible.builtin.template:
    src: "{{ role_path }}/files/11-crio-ipv4-bridge.conflist.j2"
    dest: /etc/cni/net.d/11-crio-ipv4-bridge.conflist
    mode: '0644'

- name: Backup original crio.conf
  ansible.builtin.command: mv /etc/crio/crio.conf /etc/crio/crio.conf_backup
  changed_when: false

- name: Copy crio.conf file to the server
  ansible.builtin.copy:
    src: "{{ role_path }}/files/crio.conf"
    dest: /etc/crio/crio.conf
    mode: '0644'

- name: Append to /etc/subuid containers
  ansible.builtin.lineinfile:
    path: /etc/subuid
    line: "containers:231072:6553600"
    create: "yes"
    mode: '0644'

- name: Append to /etc/subgid containers
  ansible.builtin.lineinfile:
    path: /etc/subgid
    line: "containers:231072:6553600"
    create: "yes"
    mode: '0644'

- name: Disable swap
  ansible.builtin.command: swapoff -a
  changed_when: false

- name: Comment out swap entry in /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '.*swap.*'
    line: '#&'
    backup: "yes"

- name: Disable IPv6 system-wide (net.ipv6.conf.all.disable_ipv6)
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    line: "net.ipv6.conf.all.disable_ipv6 = 1"
    create: "yes"
    mode: '0644'

- name: Disable IPv6 system-wide (net.ipv6.conf.default.disable_ipv6)
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    line: "net.ipv6.conf.default.disable_ipv6 = 1"
    create: "yes"
    mode: '0644'

- name: Apply sysctl changes
  ansible.builtin.command: sysctl -p
  changed_when: false

- name: Comment out IPv6 localhost (::1) in /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^::1'
    line: '#::1'

- name: Restart CRI-O service
  ansible.builtin.systemd:
    name: crio
    state: restarted
    enabled: "yes"

- name: Delete CNI interface (cni0)
  ansible.builtin.command: ip link delete cni0
  changed_when: false
