# - name: Reinstall K3S with CRI-O
#   shell: |
#     export K3S_KUBECONFIG_MODE="{{ sysbox_install_k3s_kubeconfig_mode }}"
#     export INSTALL_K3S_EXEC="{{ sysbox_install_k3s_install_exec }}"
#     export INSTALL_K3S_VERSION="{{ sysbox_install_k3s_version }}"
#     curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL=$INSTALL_K3S_VERSION sh -
#   args:
#     executable: /bin/bash

- name: Copy k3s.service file to the server
  ansible.builtin.copy:
    src: "{{ role_path }}/files/k3s-agent.service"
    dest: /etc/systemd/system/k3s-agent.service
    mode: '0644'

- name: Ensure the service is reloaded after changes
  ansible.builtin.systemd:
    name: k3s-agent
    state: reloaded

- name: Restart K3S Agent service
  ansible.builtin.systemd:
    name: k3s-agent
    state: restarted
    enabled: "yes"

- name: Fetch hostname
  ansible.builtin.command: hostname
  register: hostname_result
  changed_when: false

- name: Store hostname in a custom variable
  ansible.builtin.set_fact:
    my_hostname: "{{ hostname_result.stdout }}"

- name: Label node for sysbox install
  ansible.builtin.shell: |
    kubectl label nodes {{ my_hostname }} sysbox-install=yes
  args:
    executable: /bin/bash
  delegate_to: localhost
  changed_when: false

- name: Update apt sources to old releases
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    regexp: 'http://es.archive.ubuntu.com/ubuntu'
    line: 'http://old-releases.ubuntu.com/ubuntu'
    state: present
  notify:
    - Update apt cache

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: "yes"

- name: Install jq
  ansible.builtin.apt:
    name: jq
    state: present

- name: Download Sysbox package
  ansible.builtin.get_url:
    url: https://downloads.nestybox.com/sysbox/releases/v0.6.5/sysbox-ce_0.6.5-0.linux_amd64.deb
    dest: /tmp/sysbox-ce_0.6.5-0.linux_amd64.deb
    mode: '0770'

- name: Install Sysbox package
  ansible.builtin.apt:
    deb: /tmp/sysbox-ce_0.6.5-0.linux_amd64.deb
    state: present

- name: Install Sysbox Daemon applying the changes of the yaml
  ansible.builtin.shell: |
    kubectl apply -f {{ playbook_dir }}/roles/sysbox/install/files/sysbox.yaml
  args:
    executable: /bin/bash
  delegate_to: localhost
  changed_when: false
